[Feat] Local 토너먼트 플레이어 닉네임 입력 검사
authenticity-house/ft_transcendence pull request #167
Opened 2024-04-21 13:36 UTC by JeongRon

## 🚅 PR 한 줄 요약
- Local 토너먼트 플레이어 닉네임 입력 검사

## 🧑‍💻 PR 세부 내용
- Local -> 토너먼트 -> 플레이어 닉네임 입력 후 -> **시작 버튼**을 누르면 입력 받은 닉네임들을 검사합니다.
- 닉네임 검사를 진행하면서 오류가 발견되면 게임 시작을 하지 않고, 참여 인원 + - 버튼의 오른쪽에 에러 메시지를 텍스트로 띄우도록 UI를 작성했습니다. 
### 닉네임 입력 검사 규칙
1. 입력한 길이가 0인 닉네임이 있을 시, 에러메시지 - '입력하지 않은 닉네임이 존재합니다.'
2. 공백(SpaceBar)이 포함된 경우, 에러메시지 - '닉네임에 공백이 포함되어 있습니다.'
3. 중복된 닉네임이 있는 경우, 에러메시지 - '중복된 닉네임이 존재합니다.'

## 📸 스크린샷
1. 입력한 길이가 0인 닉네임이 있을 시, 에러메시지 - '입력하지 않은 닉네임이 존재합니다.'
<img width="600" alt="스크린샷 2024-04-21 오후 10 32 19" src="https://github.com/authenticity-house/ft_transcendence/assets/83465749/a3815200-91d1-4836-9e8c-0dbe6eaf001f">

2. 공백(SpaceBar)이 포함된 경우, 에러메시지 - '닉네임에 공백이 포함되어 있습니다.'
<img width="600" alt="스크린샷 2024-04-21 오후 10 33 45" src="https://github.com/authenticity-house/ft_transcendence/assets/83465749/f38c763a-6d76-4238-b04e-1a38083b9c23">

3. 중복된 닉네임이 있는 경우, 에러메시지 - '중복된 닉네임이 존재합니다.'
<img width="600" alt="스크린샷 2024-04-21 오후 10 35 54" src="https://github.com/authenticity-house/ft_transcendence/assets/83465749/ee29716a-7ff9-4455-9343-63fbe1e15bc9">

## 📚 관련 이슈
#166

2024-04-23 07:57 UTC, wonyangs requested changes
공백, 중복, 닉네임이 입력되지 않은 경우 예외처리가 잘된 것을 확인했습니다!
다만 닉네임의 최대 길이도 막으면 좋을 것 같네요.
지금은 무한정 들어가서 서버에 문제를 일으킬 수도 있을 것 같습니당

이 부분만 수정해주시면 좋을 것 같아요!

2024-04-24 06:02 UTC, JeongRon commented
닉네임을 최대 12자까지 설정하는 코드를 추가했습니다!

2024-04-24 06:02 UTC, wonyangs submitted a review, later dismissed

2024-04-24 06:40 UTC, irenee-14 approved these changes
닉네임 체크를 하지 않아 빈 채로 게임이 시작되었을 경우 진행이 제대로 안되는 문제가 있었는데 해결된 것 같습니다! 에러 문구를 띄우는 것도 좋네요 LGTM~

2024-04-24 06:51 UTC, wonyangs approved these changes

2024-04-24 06:53 UTC, merged