[Feat] 유저 노드 이벤트 추가, 친구 모달 구현 및 모달 전환 구현
authenticity-house/ft_transcendence pull request #184
Opened 2024-04-29 07:33 UTC by dbwhdtjr0457

## 🚅 PR 한 줄 요약

유저 노드 이벤트 추가, 친구 모달 구현 및 모달 전환 구현

## 🧑‍💻 PR 세부 내용

- 유저 노드 이벤트 추가
  - 호버 시 시각화
- 친구 모달 구현 및 모달 전환 구현
  - 유저 노드 클릭 시 해당 유저 모달로 전환
  - 데이터 fetch해서 연결

## 📸 스크린샷

<img width="1458" alt="Screen Shot 2024-04-29 at 4 32 50 PM" src="https://github.com/authenticity-house/ft_transcendence/assets/49023654/dc4ab828-6a8a-4da7-ba56-c190605efdfc">

<img width="1701" alt="Screen Shot 2024-04-29 at 4 33 06 PM" src="https://github.com/authenticity-house/ft_transcendence/assets/49023654/83bfb6d1-78c8-4d98-aade-68319d1925ba">

## 📚 관련 이슈

#178

2024-04-29 07:57 UTC, irenee-14 commented on FE/src/components/modal/profile_modal/UserSearchContent.js
> +					})
검색된 사용자가 없을때 204가 오는데, 이에 대한 처리가 없어서 res.json()을 받아오지 못하는 오류가 생깁니다! 204일때 검색 창을 비워주시면 될 것 같습니다~

2024-04-29 07:57 UTC, irenee-14 commented on FE/src/components/modal/profile_modal/UserSearchContent.js
> +		const userSearchButton = document.querySelector('.user-search-button');
유저 검색 모달에서 다른 모달으로 이동했다가, 다시 유저 검색 모달에 돌아와 빈 문자열로 검색을 하면 alert이 여러번 뜨는 오류가 있습니다! eventListener을 다는 부분을 수정해야 할 것 같습니다!

2024-04-29 07:57 UTC, irenee-14 commented on FE/src/components/modal/profile_modal/MyInfoContent.js
> +							<div class="my-info-content-image"></div>
프로필 이미지와 닉네임 부분이 오른쪽 박스 컨테이너의 중앙 혹은 하단과 맞게 변경되었으면 좋겠습니다! 지금은 이미지가 너무 위쪽에 붙어있어 보여요..!

2024-04-30 04:25 UTC, irenee-14 approved these changes
검색 결과가 없는 부분과 검색할 단어를 입력하지 않았을 때 모두 alert을 띄우는 것 확인했습니다! 모달도 이제 많이 완성되어 가네요~ LGTM~~

2024-04-30 06:48 UTC, mingxoxo commented on .DS_Store
파일 삭제 부탁드립니다!!

2024-04-30 06:57 UTC, mingxoxo requested changes
모달에서 검색과 알럿창이 잘 뜨는 것을 확인했습니다!

현재 API 구현을 할 때 본인도 포함해서 검색이 되도록 되어있으니까 본인에게도 친구추가 버튼이 나오네요..! 이건 어떻게 처리할 지 고민을 좀 해봐야 할 것 같습니다..

그리고 `.DS_Store`파일이 .gitignore에 제대로 포함이 안되있는 것 같습니다. 삭제하고 확인 부탁드립니다!

2024-04-30 06:57 UTC, mingxoxo commented on FE/src/components/modal/profile_modal/GetContent.js
> +			});
여기서 403에 대한 처리는 이후 추가될 예정인가요?
중간에 세션이 만료되었을 경우 403이 반환될 수 있습니다.

2024-04-30 07:13 UTC, mingxoxo commented on FE/src/constants/apiConfig.js
> +		MY_FRIEND_URL: `${USERS_URL}friend/`
`${USERS_URL}friends/`로 고쳐주세요!

2024-04-30 07:24 UTC, dbwhdtjr0457 commented on FE/src/components/modal/profile_modal/GetContent.js
> +			});
하던 거 끝내고 예외처리는 차근차근해보겟습니다

2024-04-30 07:25 UTC, dbwhdtjr0457 commented on FE/src/constants/apiConfig.js
> +		MY_FRIEND_URL: `${USERS_URL}friend/`
이거는 지금 하는 중인데 잘못 커밋된 거 ㅎㅎ

2024-04-30 10:04 UTC, JeongRon approved these changes
친구 검색이 잘 이루어지는 것을 확인했습니다!! LGTM 👍👍

2024-04-30 10:18 UTC, merged