[Feat] 모달 - 내정보 수정 UI
authenticity-house/ft_transcendence pull request #205
Opened 2024-05-02 13:17 UTC by JeongRon

## 🚅 PR 한 줄 요약
- 모달 - 내정보 수정 UI
## 🧑‍💻 PR 세부 내용
- 내정보 수정 UI를 어떻게 만들지 고민하다가 History가 더욱 복잡해질 수 있으므로 모달안의 모달로 이동하거나 페이지로 이동하는 것을 하지 않고, 해당 모달 창에서 해결을 하게끔 UI를 작성했습니다.

- 프로필 이미지 변경, 닉네임 변경, 비밀번호 변경 UI 만들기

- 닉네임과 비밀번호 확인 유효 검사는 코드에 없습니다! UI만 했어요 😅

## 📸 스크린샷

https://github.com/authenticity-house/ft_transcendence/assets/83465749/2c375f6a-e477-4dc2-8a41-f7f4cbd0cf08

## 📚 관련 이슈
#188

2024-05-02 13:27 UTC, mingxoxo commented on FE/public/css/font.css
지금은 cdn 경로가 잘 동작해서 다시 rollback 부탁드립니다!

2024-05-02 13:27 UTC, mingxoxo commented on FE/public/index.html
이것도 같이 돌려주세요!

2024-05-02 13:30 UTC, JeongRon commented on FE/public/css/font.css
오 깜빡했네요 😅

2024-05-03 07:28 UTC, dbwhdtjr0457 approved these changes
내 정보 수정 UI 구현한 부분 코드 확인 및 테스트 확인했습니다. LGTM!

2024-05-03 07:47 UTC, mingxoxo requested changes
비밀번호 변경에 취소 버튼이 생긴것을 확인했습니다.
닉네임 변경 취소 버튼이 아직 구현이 되지 않아 추가 구현 부탁드립니다!

2024-05-03 09:13 UTC, mingxoxo approved these changes
비밀번호 변경과 더불어 닉네임 변경 취소 버튼도 잘 동작하는 것을 확인했습니다. LGTM~!

2024-05-03 09:48 UTC, irenee-14 approved these changes
닉네임 변경을 하려고 할 떄, 수정 완료와 수정 취소 버튼이 잘 작동하고, 비밀번호 수정 버튼을 눌렀을때도, 변경을 위한 input box가 잘 나타나는 것을 확인했습니다. LGTM~~

2024-05-03 09:48 UTC, dbwhdtjr0457 approved these changes

2024-05-03 09:50 UTC, merged